project_id = "ytdfwkchsumgdvcroaqg"

[functions.analyze-lead-profile]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.recalculate-mql]
verify_jwt = false

[functions.wasender-whatsapp]
verify_jwt = false

[functions.wasender-webhook]
verify_jwt = false

[functions.infobip-call]
verify_jwt = false

[functions.trigger-webhook]
verify_jwt = false

[functions.receive-webhook]
verify_jwt = false

[functions.create-team-member]
verify_jwt = false

[functions.list-team-members]
verify_jwt = false

[functions.update-team-member]
verify_jwt = false
