project_id = "ytdfwkchsumgdvcroaqg"

[functions.analyze-lead]
verify_jwt = false

[functions.analyze-lead-profile]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.recalculate-mql]
verify_jwt = false

[functions.wasender-whatsapp]
verify_jwt = false

[functions.wasender-webhook]
verify_jwt = false

[functions.twilio-call]
verify_jwt = false

[functions.trigger-webhook]
verify_jwt = false

[functions.receive-webhook]
verify_jwt = false
