project_id = "ytdfwkchsumgdvcroaqg"

[functions.analyze-lead]
verify_jwt = false

[functions.analyze-lead-profile]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.recalculate-mql]
verify_jwt = false
